# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-19 19:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registracia',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 19, 19, 52, 25, 633687, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registracia',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 3, 19, 19, 52, 29, 681232, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
