# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-03-12 13:33
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0002_auto_20160319_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='registracia',
            name='stupen_studia',
            field=models.CharField(choices=[('1', 'Stredná škola'), ('2', 'Maturitný ročník'), ('3', 'Bakalárske štúdium'), ('4', 'Magisterské štúdium'), ('5', 'Absolvent (PhD.)')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='registracia',
            name='token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
