# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-10-28 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reg', '0003_auto_20170312_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='registracia',
            name='ocakavanie',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='registracia',
            name='okolie',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='registracia',
            name='smerovanie',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='registracia',
            name='list',
            field=models.FileField(null=True, upload_to='uploads/list/'),
        ),
        migrations.AlterField(
            model_name='registracia',
            name='uspech',
            field=models.TextField(default=''),
        ),
    ]
